server:
  port: 9090

spring:
  redis:
    database: 0
    host: 192.168.1.118
    port: 6379
    # password: 123456
    max-active: 10
    max-wait: 500
    max-idle: 5
    min-idle: 1
    timeout: 2000
  datasource:
    url: jdbc:mysql://192.168.1.118:3306/rainbow?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: zhang
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

encrypt:
  secret: 123


curator:
  retryCount: 5
  elapsedTimeMs: 5000
  connectString: 192.168.1.118:2181
  sessionTimeoutMs: 60000
  connectionTimeoutMs: 5000

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.milchstrabe.rainbow.biz.domain.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# ===================================================================
# fastdfs config
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list:            #TrackerList , support multi
    - 192.168.1.118:22122
